import java.awt.Color;
import javax.swing.JOptionPane;

/*
 
 This is a simple game of Tic Tac Toe. Enjoy!
 */

/**
 *
 * @author somneel saha
 */
public class TicTacToe extends javax.swing.JFrame {
     private int  board[][]=new int[3][3];
     private int counter=0;
     
    /**
     * Creates new form Game
     */
    public TicTacToe() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jInternalFrame2 = new javax.swing.JInternalFrame();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        topLeft = new javax.swing.JButton();
        topMiddle = new javax.swing.JButton();
        topRight = new javax.swing.JButton();
        middleLeft = new javax.swing.JButton();
        middleMiddle = new javax.swing.JButton();
        middleRight = new javax.swing.JButton();
        bottomLeft = new javax.swing.JButton();
        bottomMiddle = new javax.swing.JButton();
        bottomRight = new javax.swing.JButton();
        resetButton = new javax.swing.JButton();

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        jInternalFrame2.setVisible(true);

        javax.swing.GroupLayout jInternalFrame2Layout = new javax.swing.GroupLayout(jInternalFrame2.getContentPane());
        jInternalFrame2.getContentPane().setLayout(jInternalFrame2Layout);
        jInternalFrame2Layout.setHorizontalGroup(
            jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame2Layout.setVerticalGroup(
            jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel1.setText("Score:");

        jTextPane1.setText("Score:");
        jScrollPane2.setViewportView(jTextPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tic-Tac-Toe");

        topLeft.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        topLeft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                topLeftActionPerformed(evt);
            }
        });

        topMiddle.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        topMiddle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                topMiddleActionPerformed(evt);
            }
        });

        topRight.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        topRight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                topRightActionPerformed(evt);
            }
        });

        middleLeft.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        middleLeft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                middleLeftActionPerformed(evt);
            }
        });

        middleMiddle.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        middleMiddle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                middleMiddleActionPerformed(evt);
            }
        });

        middleRight.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        middleRight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                middleRightActionPerformed(evt);
            }
        });

        bottomLeft.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        bottomLeft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bottomLeftActionPerformed(evt);
            }
        });

        bottomMiddle.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        bottomMiddle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bottomMiddleActionPerformed(evt);
            }
        });

        bottomRight.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        bottomRight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bottomRightActionPerformed(evt);
            }
        });

        resetButton.setText("Reset");
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bottomLeft, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                    .addComponent(middleLeft, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(topLeft, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(topMiddle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(middleMiddle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bottomMiddle, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bottomRight, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(topRight, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                        .addComponent(resetButton)
                        .addGap(46, 46, 46))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(middleRight, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(topRight, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(topLeft, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(resetButton))
                    .addComponent(topMiddle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(middleLeft, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(middleMiddle, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(middleRight, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bottomMiddle, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bottomRight, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bottomLeft, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void topLeftActionPerformed(java.awt.event.ActionEvent evt) {                                        
       if(counter%2==0)
       {
           topLeft.setText("X");
           board[0][0]=1;
           topLeft.setForeground(Color.RED);
       }
       else{
           topLeft.setText("O");
           board[0][0]=2;
           topLeft.setForeground(Color.BLACK);
       }
       counter++;
       check();
    }                                       

    private void topMiddleActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
        
        if(counter%2==0)
       {
           topMiddle.setText("X");
           board[0][1]=1;
           topMiddle.setForeground(Color.RED);
       }
       else{
           topMiddle.setText("O");
           board[0][1]=2;
           topMiddle.setForeground(Color.BLACK);
       }
        counter++;
       check();
    }                                         

    private void topRightActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        if(counter%2==0)
       {
           topRight.setText("X");
           board[0][2]=1;
           topRight.setForeground(Color.RED);
       }
       else{
           topRight.setText("O");
           board[0][2]=2;
           topRight.setForeground(Color.BLACK);
       }
        counter++;
       check();
    }                                        

    private void middleLeftActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
        if(counter%2==0)
       {
           middleLeft.setText("X");
           board[1][0]=1;
           middleLeft.setForeground(Color.RED);
       }
       else{
           middleLeft.setText("O");
           board[1][0]=2;
           middleLeft.setForeground(Color.BLACK);
       }
        counter++;
       check();
    }                                          

    private void middleMiddleActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
        if(counter%2==0)
       {
           middleMiddle.setText("X");
           board[1][1]=1;
           middleMiddle.setForeground(Color.RED);
           
       }
       else{
           middleMiddle.setText("O");
           board[1][1]=2;
           middleMiddle.setForeground(Color.BLACK);
       }
        counter++;
       check();
    }                                            

    private void middleRightActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
        if(counter%2==0)
       {
           middleRight.setText("X");
           board[1][2]=1;
           middleRight.setForeground(Color.RED);
       }
       else{
           middleRight.setText("O");
           board[1][2]=2;
           middleRight.setForeground(Color.BLACK);
       }
        counter++;
       check();
    }                                           

    private void bottomLeftActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
        if(counter%2==0)
       {
          bottomLeft.setText("X");
           board[2][0]=1;
           bottomLeft.setForeground(Color.RED);
       }
       else{
           bottomLeft.setText("O");
           board[2][0]=2;
           bottomLeft.setForeground(Color.BLACK);
       }
        counter++;
       check();
    }                                          

    private void bottomMiddleActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
        if(counter%2==0)
       {
          bottomMiddle.setText("X");
           board[2][1]=1;
           bottomMiddle.setForeground(Color.RED);
       }
       else{
           bottomMiddle.setText("O");
           board[2][1]=2;
           bottomMiddle.setForeground(Color.BLACK);
       }
        counter++;
       check();
    }                                            

    private void bottomRightActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
        if(counter%2==0)
       {
          bottomRight.setText("X");
           board[2][2]=1;
           bottomRight.setForeground(Color.RED);
       }
       else{
           bottomRight.setText("O");
           board[2][2]=2;
           bottomRight.setForeground(Color.BLACK);
       }
        counter++;
       check();
    }                                           

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
        reset();
    }                                           

    /**
     * @param args the command line arguments
     */
    private void check()
    {
        if((board[0][0]==1 && board[0][1]==1 && board[0][2]==1)||(board[1][0]==1 && board[1][1]==1 && board[1][2]==1)||(board[2][0]==1 && board[2][1]==1 && board[2][2]==1)||(board[0][0]==1 && board[1][1]==1 && board[2][2]==1)||(board[0][2]==1 && board[1][1]==1 && board[2][0]==1)||(board[0][0]==1 && board[1][0]==1 && board[2][0]==1)||(board[0][1]==1 && board[1][1]==1 && board[2][1]==1)||(board[0][2]==1 && board[1][2]==1 && board[2][2]==1))
        {
            JOptionPane.showMessageDialog(this,"X has won");reset();
        }
        if((board[0][0]==2 && board[0][1]==2 && board[0][2]==2)||(board[1][0]==2 && board[1][1]==2 && board[1][2]==2)||(board[2][0]==2 && board[2][1]==2 && board[2][2]==2)||(board[0][0]==2 && board[1][1]==2 && board[2][2]==2)||(board[0][2]==2 && board[1][1]==2 && board[2][0]==2)||(board[0][0]==2 && board[1][0]==2 && board[2][0]==2)||(board[0][1]==2 && board[1][1]==2 && board[2][1]==2)||(board[0][2]==2 && board[1][2]==2 && board[2][2]==2))
        {
            JOptionPane.showMessageDialog(this,"O has won");reset();
        }
        if(board[0][0]!=0 && board[0][1]!=0 && board[0][2]!=0 && board[1][0]!=0&&board[1][1]!=0&&board[1][2]!=0&&board[2][0]!=0&&board[2][1]!=0&&board[2][2]!=0)
        {
            JOptionPane.showMessageDialog(this,"Cats Game!");
            reset();
            
        }
    }
    private void reset()
    {
        counter=0;
        for(int i=0;i<board.length;i++)
            {
                for(int j=0;j<board.length;j++)
                {
                    board[i][j]=0;
                }
            }
        topLeft.setText("");
        topMiddle.setText("");
        topRight.setText("");
        middleLeft.setText("");
        middleMiddle.setText("");
        middleRight.setText("");
        bottomLeft.setText("");
        bottomMiddle.setText("");
        bottomRight.setText("");
        System.out.println("Board Reset!");
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TicTacToe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TicTacToe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TicTacToe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TicTacToe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TicTacToe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton bottomLeft;
    private javax.swing.JButton bottomMiddle;
    private javax.swing.JButton bottomRight;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JInternalFrame jInternalFrame2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JButton middleLeft;
    private javax.swing.JButton middleMiddle;
    private javax.swing.JButton middleRight;
    private javax.swing.JButton resetButton;
    private javax.swing.JButton topLeft;
    private javax.swing.JButton topMiddle;
    private javax.swing.JButton topRight;
    // End of variables declaration                   
}
